### ISSUE TITLE
Add donation (info + donation form) must have user story backlog

### ISSUE THREAD

**Issue by yildiztugba** [yildiztugba/HYKWebsite#24]
You will add **Must have** story for **donation** (info +form).

Format:
user story name: As a [type of user] I want to [do something] so that [I achieve some goal]
Given [context] when [a specific action is performed] then [a set of consequences should occur]. 

[USER STORY EXAMPLES 1](https://github.com/firity/HYF-GROUP2/blob/main/planning/backlog.md)
[USER STORY EXAMPLES 2](https://github.com/sheybusta/loruki-website/blob/main/planning/backlog.md)
[USER STORY EXAMPLES 3](https://github.com/sabanyelkenci/loruki-website/blob/main/planning/backlog.md)

**Comment by Dabrytskaya** [comment]
@yildiztugba I think it's not must have) maybe even could have)

**Comment by yildiztugba** [comment]
I think it is important for website owner:) shall we do it with should have? 😀
